version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      ruby-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "gems"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
    
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      rust-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "cargo"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"